export const TYPES = {
    FILTER_PRODUCTS_BY_CATEGORY: 'FILTER_PRODUCTS_BY_CATEGORY',
    FILTER_PRODUCTS_BY_COMERCE: 'FILTER_PRODUCTS_BY_COMERCE',
    FILTER_PRODUCTS_BY_SEARCH: 'FILTER_PRODUCTS_BY_SEARCH'
}