export const TYPES = {
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_COMERCES_SUCCESS: 'FETCH_COMERCES_SUCCESS',
    FILTER_PRODUCTS_BY_CATEGORY: 'FILTER_PRODUCTS_BY_CATEGORY',
    FILTER_PRODUCTS_BY_COMERCE: 'FILTER_PRODUCTS_BY_COMERCE',
    FILTER_PRODUCTS_BY_SEARCH: 'FILTER_PRODUCTS_BY_SEARCH'
}